/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7Q2kKTTfJ4NHrVPwfjBiGV
// Component: wRYUjyQykckx

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: _MWZyCmj9Poj/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 7Q2kKTTfJ4NHrVPwfjBiGV/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 7Q2kKTTfJ4NHrVPwfjBiGV/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 7Q2kKTTfJ4NHrVPwfjBiGV/projectcss
import sty from "./PlasmicStoryFrame.module.css"; // plasmic-import: wRYUjyQykckx/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 2D7jq9Mtq-9Z/icon
import ChevronUpSvgIcon from "./icons/PlasmicIcon__ChevronUpSvg"; // plasmic-import: FGtDNcqmugkF/icon
import ChevronDownSvgIcon from "./icons/PlasmicIcon__ChevronDownSvg"; // plasmic-import: -nloqc0-FJ1X/icon

createPlasmicElementProxy;

export type PlasmicStoryFrame__VariantMembers = {
  stage: "_1" | "_2" | "_3" | "_4" | "_5";
};
export type PlasmicStoryFrame__VariantsArgs = {
  stage?: SingleChoiceArg<"_1" | "_2" | "_3" | "_4" | "_5">;
};
type VariantPropType = keyof PlasmicStoryFrame__VariantsArgs;
export const PlasmicStoryFrame__VariantProps = new Array<VariantPropType>(
  "stage"
);

export type PlasmicStoryFrame__ArgsType = {
  stage2?: string;
  onStage2Change?: (val: string) => void;
};
type ArgPropType = keyof PlasmicStoryFrame__ArgsType;
export const PlasmicStoryFrame__ArgProps = new Array<ArgPropType>(
  "stage2",
  "onStage2Change"
);

export type PlasmicStoryFrame__OverridesType = {
  storyFrame?: Flex__<"div">;
};

export interface DefaultStoryFrameProps {
  stage2?: string;
  onStage2Change?: (val: string) => void;
  stage?: SingleChoiceArg<"_1" | "_2" | "_3" | "_4" | "_5">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStoryFrame__RenderFunc(props: {
  variants: PlasmicStoryFrame__VariantsArgs;
  args: PlasmicStoryFrame__ArgsType;
  overrides: PlasmicStoryFrame__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "stage",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.stage2;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.stage
      },
      {
        path: "stage2",
        type: "writable",
        variableType: "text",

        valueProp: "stage2",
        onChangeProp: "onStage2Change"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();

  return (
    <div
      data-plasmic-name={"storyFrame"}
      data-plasmic-override={overrides.storyFrame}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        sty.storyFrame,
        {
          [sty.storyFramestage__1]: hasVariant($state, "stage", "_1"),
          [sty.storyFramestage__2]: hasVariant($state, "stage", "_2"),
          [sty.storyFramestage__3]: hasVariant($state, "stage", "_3"),
          [sty.storyFramestage__4]: hasVariant($state, "stage", "_4")
        }
      )}
    >
      <Button
        className={classNames("__wab_instance", sty.button__wDZaZ, {
          [sty.buttonstage__1__wDZaZrArIv]: hasVariant($state, "stage", "_1"),
          [sty.buttonstage__4__wDZaZgfxDh]: hasVariant($state, "stage", "_4")
        })}
        onClick={async event => {
          const $steps = {};

          $steps["updateStage2"] = true
            ? (() => {
                const actionArgs = {
                  variable: {
                    objRoot: $state,
                    variablePath: ["stage2"]
                  },
                  operation: 0,
                  value: ($state.stage2 =
                    $state.stage2 === "_1"
                      ? $state.stage2
                      : $state.stage2.replace(
                          /_(\d+)/,
                          (_, num) => `_${parseInt(num) - 1}`
                        ))
                };
                return (({ variable, value, startIndex, deleteCount }) => {
                  if (!variable) {
                    return;
                  }
                  const { objRoot, variablePath } = variable;

                  $stateSet(objRoot, variablePath, value);
                  return value;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateStage2"] != null &&
            typeof $steps["updateStage2"] === "object" &&
            typeof $steps["updateStage2"].then === "function"
          ) {
            $steps["updateStage2"] = await $steps["updateStage2"];
          }
        }}
      />

      <div
        className={classNames(projectcss.all, sty.freeBox__ztkw6, {
          [sty.freeBoxstage__1__ztkw6RArIv]: hasVariant($state, "stage", "_1"),
          [sty.freeBoxstage__2__ztkw6XVhH]: hasVariant($state, "stage", "_2"),
          [sty.freeBoxstage__3__ztkw6KOuye]: hasVariant($state, "stage", "_3"),
          [sty.freeBoxstage__4__ztkw6GfxDh]: hasVariant($state, "stage", "_4")
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__mmWsI,
            {
              [sty.textstage__1__mmWsIrArIv]: hasVariant($state, "stage", "_1"),
              [sty.textstage__2__mmWsIxVhH]: hasVariant($state, "stage", "_2"),
              [sty.textstage__3__mmWsIkOuye]: hasVariant($state, "stage", "_3"),
              [sty.textstage__4__mmWsIgfxDh]: hasVariant($state, "stage", "_4")
            }
          )}
        >
          {
            "\u062f\u0627\u0633\u062a\u0627\u0646 \u0627\u0644\u0645\u067e\u06cc\u0627\u062f"
          }
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kDqVm,
            {
              [sty.textstage__1__kDqVmrArIv]: hasVariant($state, "stage", "_1"),
              [sty.textstage__2__kDqVmxVhH]: hasVariant($state, "stage", "_2"),
              [sty.textstage__3__kDqVmkOuye]: hasVariant($state, "stage", "_3"),
              [sty.textstage__4__kDqVmGfxDh]: hasVariant($state, "stage", "_4")
            }
          )}
        >
          {"\u062a\u0648\u0644\u062f \u06cc\u06a9 \u0631\u0648\u06cc\u0627\n"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__nry3S,
            {
              [sty.textstage__1__nry3SrArIv]: hasVariant($state, "stage", "_1"),
              [sty.textstage__2__nry3SxVhH]: hasVariant($state, "stage", "_2"),
              [sty.textstage__3__nry3SkOuye]: hasVariant($state, "stage", "_3"),
              [sty.textstage__4__nry3SgfxDh]: hasVariant($state, "stage", "_4")
            }
          )}
        >
          {hasVariant($state, "stage", "_4")
            ? "\u062f\u0631 \u062a\u06cc\u0631 \u0645\u0627\u0647 \u0633\u0627\u0644 1393 \u0627\u0648\u0644\u06cc\u0646 \u0642\u062f\u0645 \u0647\u0627"
            : hasVariant($state, "stage", "_3")
            ? "\u062f\u0631 \u062a\u06cc\u0631 \u0645\u0627\u0647 \u0633\u0627\u0644 1393 \u0627\u0648\u0644\u06cc\u0646 \u0642\u062f\u0645 \u0647\u0627"
            : hasVariant($state, "stage", "_2")
            ? "\u062f\u0631 \u062a\u06cc\u0631 \u0645\u0627\u0647 \u0633\u0627\u0644 1393 \u0627\u0648\u0644\u06cc\u0646 \u0642\u062f\u0645 \u0647\u0627"
            : "\u062f\u0631 \u062a\u06cc\u0631 \u0645\u0627\u0647 \u0633\u0627\u0644 1393 \u0627\u0648\u0644\u06cc\u0646 \u0642\u062f\u0645 \u0647\u0627 ."}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__mwlZy,
            {
              [sty.textstage__1__mwlZyrArIv]: hasVariant($state, "stage", "_1"),
              [sty.textstage__2__mwlZyxVhH]: hasVariant($state, "stage", "_2"),
              [sty.textstage__3__mwlZykOuye]: hasVariant($state, "stage", "_3"),
              [sty.textstage__4__mwlZyGfxDh]: hasVariant($state, "stage", "_4")
            }
          )}
        >
          {
            "\n\u0628\u0631\u0627\u06cc \u0631\u0642\u0645 \u0632\u062f\u0646 \u0631\u0648\u06cc\u0627\u06cc\u06cc \u0646\u0648 \u062f\u0631 \u0634\u0647\u0631 \u0627\u06cc\u0644\u0627\u0645 \u0628\u0631\u062f\u0627\u0634\u062a\u06cc\u0645."
          }
        </div>
      </div>
      <PlasmicImg__
        alt={""}
        className={classNames(sty.img___0ReO8, {
          [sty.imgstage__1___0ReO8RArIv]: hasVariant($state, "stage", "_1"),
          [sty.imgstage__2___0ReO8XVhH]: hasVariant($state, "stage", "_2"),
          [sty.imgstage__3___0ReO8KOuye]: hasVariant($state, "stage", "_3"),
          [sty.imgstage__4___0ReO8GfxDh]: hasVariant($state, "stage", "_4"),
          [sty.imgstage__5___0ReO8P01Xv]: hasVariant($state, "stage", "_5")
        })}
        displayHeight={"100%"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"auto"}
        loading={"lazy"}
        src={
          hasVariant($state, "stage", "_1")
            ? {
                src: "/plasmic/main_ui/images/_9Svg.svg",
                fullWidth: 1080,
                fullHeight: 606.75,
                aspectRatio: 1.779975
              }
            : {
                src: "/plasmic/main_ui/images/_999Png.png",
                fullWidth: 720,
                fullHeight: 404,
                aspectRatio: undefined
              }
        }
      />

      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__wGEnF, {
          [sty.imgstage__1__wGEnFrArIv]: hasVariant($state, "stage", "_1"),
          [sty.imgstage__2__wGEnFxVhH]: hasVariant($state, "stage", "_2"),
          [sty.imgstage__3__wGEnFkOuye]: hasVariant($state, "stage", "_3"),
          [sty.imgstage__4__wGEnFgfxDh]: hasVariant($state, "stage", "_4"),
          [sty.imgstage__5__wGEnFp01Xv]: hasVariant($state, "stage", "_5")
        })}
        displayHeight={"100%"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"auto"}
        loading={"lazy"}
        src={
          hasVariant($state, "stage", "_1")
            ? {
                src: "/plasmic/main_ui/images/_10Svg.svg",
                fullWidth: 1080,
                fullHeight: 606.75,
                aspectRatio: 1.779975
              }
            : {
                src: "/plasmic/main_ui/images/main1440X809Px1Png.png",
                fullWidth: 1440,
                fullHeight: 809,
                aspectRatio: undefined
              }
        }
      />

      <PlasmicImg__
        alt={""}
        className={classNames(sty.img___6F3Xk, {
          [sty.imgstage__1___6F3XkrArIv]: hasVariant($state, "stage", "_1"),
          [sty.imgstage__2___6F3XkxVhH]: hasVariant($state, "stage", "_2"),
          [sty.imgstage__3___6F3XkkOuye]: hasVariant($state, "stage", "_3"),
          [sty.imgstage__4___6F3XkGfxDh]: hasVariant($state, "stage", "_4"),
          [sty.imgstage__5___6F3Xkp01Xv]: hasVariant($state, "stage", "_5")
        })}
        displayHeight={hasVariant($state, "stage", "_2") ? "auto" : "100%"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={hasVariant($state, "stage", "_2") ? "auto" : "auto"}
        loading={"lazy"}
        src={
          hasVariant($state, "stage", "_1")
            ? {
                src: "/plasmic/main_ui/images/_11Svg.svg",
                fullWidth: 1080,
                fullHeight: 606.75,
                aspectRatio: 1.779975
              }
            : {
                src: "/plasmic/main_ui/images/_11Png.png",
                fullWidth: 720,
                fullHeight: 404,
                aspectRatio: undefined
              }
        }
      />

      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__hRlaC, {
          [sty.imgstage__1__hRlaCrArIv]: hasVariant($state, "stage", "_1"),
          [sty.imgstage__2__hRlaCxVhH]: hasVariant($state, "stage", "_2"),
          [sty.imgstage__3__hRlaCkOuye]: hasVariant($state, "stage", "_3"),
          [sty.imgstage__4__hRlaCgfxDh]: hasVariant($state, "stage", "_4"),
          [sty.imgstage__5__hRlaCp01Xv]: hasVariant($state, "stage", "_5")
        })}
        displayHeight={hasVariant($state, "stage", "_2") ? "auto" : "100%"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={hasVariant($state, "stage", "_2") ? "auto" : "auto"}
        loading={"lazy"}
        src={
          hasVariant($state, "stage", "_1")
            ? {
                src: "/plasmic/main_ui/images/_12Svg.svg",
                fullWidth: 1080,
                fullHeight: 606.75,
                aspectRatio: 1.779975
              }
            : {
                src: "/plasmic/main_ui/images/_12Png.png",
                fullWidth: 720,
                fullHeight: 404,
                aspectRatio: undefined
              }
        }
      />

      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__xyIox, {
          [sty.imgstage__1__xyIoxrArIv]: hasVariant($state, "stage", "_1"),
          [sty.imgstage__2__xyIoxxVhH]: hasVariant($state, "stage", "_2"),
          [sty.imgstage__3__xyIoxkOuye]: hasVariant($state, "stage", "_3"),
          [sty.imgstage__4__xyIoxGfxDh]: hasVariant($state, "stage", "_4"),
          [sty.imgstage__5__xyIoxp01Xv]: hasVariant($state, "stage", "_5")
        })}
        displayHeight={hasVariant($state, "stage", "_2") ? "auto" : "100%"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={hasVariant($state, "stage", "_2") ? "auto" : "auto"}
        loading={"lazy"}
        src={
          hasVariant($state, "stage", "_1")
            ? {
                src: "/plasmic/main_ui/images/_13Svg.svg",
                fullWidth: 1080,
                fullHeight: 606.75,
                aspectRatio: 1.779975
              }
            : {
                src: "/plasmic/main_ui/images/_13Png.png",
                fullWidth: 720,
                fullHeight: 404,
                aspectRatio: undefined
              }
        }
      />

      <div
        className={classNames(projectcss.all, sty.freeBox__zsGj, {
          [sty.freeBoxstage__2__zsGjxVhH]: hasVariant($state, "stage", "_2")
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__xUvL3, {
            [sty.freeBoxstage__1__xUvL3RArIv]: hasVariant(
              $state,
              "stage",
              "_1"
            ),
            [sty.freeBoxstage__4__xUvL3GfxDh]: hasVariant($state, "stage", "_4")
          })}
        >
          <ChevronUpSvgIcon
            className={classNames(projectcss.all, sty.svg__nk4LE, {
              [sty.svgstage__1__nk4LErArIv]: hasVariant($state, "stage", "_1")
            })}
            onClick={async event => {
              const $steps = {};

              $steps["updateStage2"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["stage2"]
                      },
                      operation: 0,
                      value: ($state.stage2 =
                        $state.stage2 === "_1"
                          ? $state.stage2
                          : $state.stage2.replace(
                              /_(\d+)/,
                              (_, num) => `_${parseInt(num) - 1}`
                            ))
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateStage2"] != null &&
                typeof $steps["updateStage2"] === "object" &&
                typeof $steps["updateStage2"].then === "function"
              ) {
                $steps["updateStage2"] = await $steps["updateStage2"];
              }
            }}
            role={"img"}
          />
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__fQ3Gc, {
          [sty.freeBoxstage__4__fQ3GcGfxDh]: hasVariant($state, "stage", "_4")
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__mlK0A, {
            [sty.freeBoxstage__1__mlK0ArArIv]: hasVariant(
              $state,
              "stage",
              "_1"
            ),
            [sty.freeBoxstage__2__mlK0AxVhH]: hasVariant($state, "stage", "_2"),
            [sty.freeBoxstage__3__mlK0AkOuye]: hasVariant(
              $state,
              "stage",
              "_3"
            ),
            [sty.freeBoxstage__4__mlK0AGfxDh]: hasVariant(
              $state,
              "stage",
              "_4"
            ),
            [sty.freeBoxstage__5__mlK0Ap01Xv]: hasVariant($state, "stage", "_5")
          })}
        >
          <ChevronDownSvgIcon
            className={classNames(projectcss.all, sty.svg__akVzf, {
              [sty.svgstage__1__akVzfrArIv]: hasVariant($state, "stage", "_1"),
              [sty.svgstage__4__akVzfGfxDh]: hasVariant($state, "stage", "_4"),
              [sty.svgstage__5__akVzfp01Xv]: hasVariant($state, "stage", "_5")
            })}
            onClick={async event => {
              const $steps = {};

              $steps["updateStage2"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["stage2"]
                      },
                      operation: 0,
                      value: ($state.stage2 =
                        $state.stage2 === "_5"
                          ? $state.stage2
                          : $state.stage2.replace(
                              /_(\d+)/,
                              (_, num) => `_${parseInt(num) + 1}`
                            ))
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateStage2"] != null &&
                typeof $steps["updateStage2"] === "object" &&
                typeof $steps["updateStage2"].then === "function"
              ) {
                $steps["updateStage2"] = await $steps["updateStage2"];
              }
            }}
            role={"img"}
          />
        </div>
      </div>
      <Button
        className={classNames("__wab_instance", sty.button__mNqd, {
          [sty.buttonstage__1__mNqDrArIv]: hasVariant($state, "stage", "_1"),
          [sty.buttonstage__4__mNqdgfxDh]: hasVariant($state, "stage", "_4")
        })}
        onClick={async event => {
          const $steps = {};

          $steps["updateStage2"] = true
            ? (() => {
                const actionArgs = {
                  variable: {
                    objRoot: $state,
                    variablePath: ["stage2"]
                  },
                  operation: 0,
                  value: ($state.stage2 =
                    $state.stage2 === "_4"
                      ? $state.stage2
                      : $state.stage2.replace(
                          /_(\d+)/,
                          (_, num) => `_${parseInt(num) + 1}`
                        ))
                };
                return (({ variable, value, startIndex, deleteCount }) => {
                  if (!variable) {
                    return;
                  }
                  const { objRoot, variablePath } = variable;

                  $stateSet(objRoot, variablePath, value);
                  return value;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateStage2"] != null &&
            typeof $steps["updateStage2"] === "object" &&
            typeof $steps["updateStage2"].then === "function"
          ) {
            $steps["updateStage2"] = await $steps["updateStage2"];
          }
        }}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  storyFrame: ["storyFrame"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  storyFrame: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStoryFrame__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStoryFrame__VariantsArgs;
    args?: PlasmicStoryFrame__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStoryFrame__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicStoryFrame__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStoryFrame__ArgProps,
          internalVariantPropNames: PlasmicStoryFrame__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStoryFrame__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "storyFrame") {
    func.displayName = "PlasmicStoryFrame";
  } else {
    func.displayName = `PlasmicStoryFrame.${nodeName}`;
  }
  return func;
}

export const PlasmicStoryFrame = Object.assign(
  // Top-level PlasmicStoryFrame renders the root element
  makeNodeComponent("storyFrame"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicStoryFrame
    internalVariantProps: PlasmicStoryFrame__VariantProps,
    internalArgProps: PlasmicStoryFrame__ArgProps
  }
);

export default PlasmicStoryFrame;
/* prettier-ignore-end */
